apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-keur
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-keur
    app.kubernetes.io/part-of: cin4s-839-0050-app
  name: devfile-sample-keur
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-keur
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-keur
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0050-tenant/cin4s-839-0050-app/devfile-sample-keur@sha256:f970d433f43f6d85633c9538c80f046e9f096ebf4db9eed6a6279372526e2df7
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
